apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: prod

# Use a patch to change the number of replicas
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: nginx
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: malefstorm.ru
    - op: replace
      path: /spec/tls/0/hosts/0
      value: malefstorm.ru
  target:
    kind: Ingress
    name: nginx-ingress

images:
  - name: registry.malefstorm.ru/malefstudio/landing
    newTag: v0.1.1