apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namePrefix: dev-

# Use a patch to change the number of replicas
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.malefstorm.ru
    - op: replace
      path: /spec/tls/0/hosts/0
      value: dev.malefstorm.ru
  target:
    kind: Ingress
    name: nginx-ingress

images:
  - name: registry.malefstorm.ru/malefstudio/landing:latest
    newTag: latest